# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: true
sudo: false
cache: packages
notifications:
  email:
    - cnieuwou@sfu.ca
before_install:
  Rscript -e 'update.packages(ask = FALSE)'
